# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Server
source:           docs
destination:      _gh_pages
host:             0.0.0.0
port:             9001
baseurl:          /
url:              http://kpowz.github.io/gus-bootstrap
encoding:         UTF-8

# Custom vars
current_version:  3.2.0
repo:             https://github.com/kpowz/gus-bootstrap

download:
  source:         https://github.com/kpowz/gus-bootstrap/archive/v3.2.0.zip
  dist:           https://github.com/kpowz/gus-bootstrap/releases/download/v3.2.0/bootstrap-3.2.0-dist.zip
